---
title: "function"
author: "Congyu Yang"
date: "2024-10-29"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(readxl)
```

# Do something simple

```{r}
x = rnorm(30,mean = 5, sd = 3)

# z score
(x - mean(x))/sd(x)
```
I want a function to compute z-score

```{r}
z_scores <-  function(x) {
  
  # conditional exection
  
  if(!is.numeric(x)){
    stop("Input must be numeric")
  }
  if(length(x) < 3){
    stop("Input must have at least three numbers.")
  }
  
  z = (x - mean(x))/sd(x)
  
  return(z)
}

z_scores(x)
```
Try my function on some other things.

```{r, error=TRUE}
z_scores(3)  # sd(3) = NA
z_scores("my name is jeff") # non-numeric argument
z_scores(c(T,T,F,T))
```

# Multiple outputs

```{r}
mean_and_sd <-  function(x) {
  
  # conditional exection
  
  if(!is.numeric(x)){
    stop("Input must be numeric")
  }
  if(length(x) < 3){
    stop("Input must have at least three numbers.")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )

}

mean_and_sd(x)
```

# Multiple Inputs

```{r}
sim_data <- tibble(
  x = rnorm(100,4,3)
)

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
```
```{r}

sim_mean_sd <- function(n,mu,sigma){
  
    sim_data <- tibble(
    x = rnorm(n,mu,sigma)
  )
    
    sim_data %>% 
      summarize(
       mean = mean(x),
       sd = sd(x)
      )
}

sim_mean_sd(100,6,3)
```
# Revisit LoTR 
```{r}
fellowship_df <- 
  read_excel("data/LotR_Words.xlsx",range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring") %>% 
  janitor::clean_names()

tower_df <- 
  read_excel("data/LotR_Words.xlsx",range = "F3:H6") %>% 
  mutate(movie = "two_towers") %>% 
  janitor::clean_names()

return_df <- 
  read_excel("data/LotR_Words.xlsx",range = "J3:L6") %>% 
  mutate(movie = "return_king") %>% 
  janitor::clean_names()
```

```{r}
readxl <- function(range,name){
   df<- 
    read_excel("data/LotR_Words.xlsx",range = range) %>%
    mutate(name = name) %>% 
    janitor::clean_names()
   
   return(df)
  
}

lotr_df <- 
  bind_rows (readxl(range = "B3:D6",name = "fellowship_ring"),
             readxl(range = "F3:H6",name = "two_towers"),
             readxl(range = "J3:L6",name = "return_king"))
```

```{r}
nsduh_table <- function(html, table_num, table_name) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent),
      name = table_name) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
  table
  
}
```


